version: '2'
services:
    odd1out-app:
        image: odd1out
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://odd1out-postgresql:5432/odd1out
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    odd1out-postgresql:
        extends:
            file: postgresql.yml
            service: odd1out-postgresql
